services:
  mongo:
    image: mongo:7
    container_name: stackit-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: preyanshmehta25/stackit-backend:latest
    container_name: stackit-backend
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/StackIt
    ports:
      - "5002:5001"
    depends_on:
      - mongo

  frontend:
    image: preyanshmehta25/stackit-frontend:latest
    container_name: stackit-frontend
    ports:
      - "5174:80"
    depends_on:
      - backend

volumes:
  mongo_data:
